# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - Infra/*
      - Infra/Terraform/*

stages:
- stage: TerraformValidate
  jobs: 
    - job: tf_validate
      pool:
       name: SelfHostedPool
      steps: 
<<<<<<< HEAD
       - task: TerraformInstaller@1
         displayName: 'Terrafom Install on the hosted agent'
         inputs:
          terraformVersion: 'latest'
       - task: TerraformTask@5
         displayName: 'Initialize Terraform' 
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: '$(System.DefaultWorkingDirectory)/Infra/Terraform/DEV'
           backendAzureRmUseEntraIdForAuthentication: false
           backendServiceArm: 'Azure subscription 1'
           backendAzureRmResourceGroupName: 'terraform-stfiles-rg01'
           backendAzureRmStorageAccountName: 'devtfstatespetclinic'
           backendAzureRmContainerName: 'terraformstaefiles'
           backendAzureRmKey: 'dev-petclinicstatefile01.tfstate'
       - task: TerraformTask@5
         displayName: 'Validate Terraform Configuration'
         inputs:
           provider: 'azurerm'
           command: 'validate'
           workingDirectory: '$(System.DefaultWorkingDirectory)/Infra/Terraform/DEV'
- stage: Dev_deploy
  condition: succeeded()
  jobs: 
    - job: terrafom_apply_dev
      pool:
        name: SelfHostedPool  
      steps: 
        - task: TerraformInstaller@1
=======
      - task: TerraformInstaller@1
         inputs:
          terraformVersion: 'latest'
       - task: TerraformTask@5
         displayName: 'Initialize Terraform' 
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: '$(System.DefaultWorkingDirectory)/Infra/Terraform/DEV'
           backendAzureRmUseEntraIdForAuthentication: false
           backendServiceArm: 'Azure subscription 1(1)(6e7256d2-7049-4f1c-a8a9-c31e1da9d40a)'
           backendAzureRmResourceGroupName: 'terraform-stfiles-rg01'
           backendAzureRmStorageAccountName: 'devtfstatespetclinic'
           backendAzureRmContainerName: 'terraformstaefiles'
           backendAzureRmKey: 'dev-petclinicstatefile01.tfstate'
       - task: TerraformTask@5
         displayName: 'Validate Terraform Configuration'
         inputs:
           provider: 'azurerm'
           command: 'validate'
           workingDirectory: '$(System.DefaultWorkingDirectory)/Infra/Terraform/DEV'
- stage: Dev_deploy
  condition: succeeded()
  jobs: 
    - job: terrafom_apply_dev
      pool:
        name: SelfHostedPool  
      steps: 
       - task: TerraformInstaller@1

         inputs:
          terraformVersion: 'latest'
       - task: TerraformTask@5
         displayName: 'Initialize Terraform'
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: '$(System.DefaultWorkingDirectory)/Infra/Terraform/DEV'
           backendAzureRmUseEntraIdForAuthentication: false
           backendServiceArm: 'Azure subscription 1'
           backendAzureRmResourceGroupName: 'terraform-stfiles-rg01'
           backendAzureRmStorageAccountName: 'devtfstatespetclinic'
           backendAzureRmContainerName: 'terraformstaefiles'
           backendAzureRmKey: 'dev-petclinicstatefile01.tfstate'
       - task: TerraformTask@5
         displayName: 'Terraform Apply'
         inputs:
           provider: 'azurerm'
           command: 'apply'
           workingDirectory: '$(System.DefaultWorkingDirectory)/Infra/Terraform/DEV'
           commandOptions: 
              -var "subscription_id=$(SUBSCRIPTION_id)"
              --auto-approve
           environmentServiceNameAzureRM: 'Azure subscription 1(6e7256d2-7049-4f1c-a8a9-c31e1da9d40a)'  
- stage: ResourceDestroy
  displayName: 'Manual Trigger to Destroy terraform resources'
  condition: succeeded()
  jobs:
  - deployment: destory
    environment: "Manual Terraform Destroy" 
  - job: 'ManualApproval'
    displayName: 'Approve Terraform Destroy'  
    pool:
      name: SelfHostedPool  
      steps: 
       - task: TerraformInstaller@1
         inputs:
          terraformVersion: 'latest'
       - task: TerraformTask@5
         inputs:
           provider: 'azurerm'
           command: 'init'
           workingDirectory: '$(System.DefaultWorkingDirectory)/Infra/Terraform/DEV'
           backendAzureRmUseEntraIdForAuthentication: false
           backendServiceArm: 'Azure subscription 1(6e7256d2-7049-4f1c-a8a9-c31e1da9d40a)'
           backendAzureRmResourceGroupName: 'terraform-stfiles-rg01'
           backendAzureRmStorageAccountName: 'devtfstatespetclinic'
           backendAzureRmContainerName: 'terraformstaefiles'
           backendAzureRmKey: 'dev-petclinicstatefile01.tfstate'
       - task: TerraformTask@5
         inputs:
         provider: 'azurerm'
         command: 'destroy'
         workingDirectory: '$(System.DefaultWorkingDirectory)/Infra/Terraform/DEV'
         commandOptions: 
            -var "subscription_id=$(SUBSCRIPTION_id)" 
            --auto-approve
         environmentServiceNameAzureRM: 'Azure subscription 1(6e7256d2-7049-4f1c-a8a9-c31e1da9d40a)'