# Step:1 Pull the MySQL image from the Docker Hub
From mysql:8.0

# Step:2 Add the DB environment variables
env MYSQL_ROOT_PASSWORD= 
env MYSQL_ALLOW_EMPTY_PASSWORD=true
env MYSQL_USER=petclinic
env MYSQL_PASSWORD=petclinic
env MYSQL_DATABASE=petclinic

# Step:4 Expose mysql port 
EXPOSE 3306

